# Generated by Django 5.1.2 on 2024-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isHighlighted',
            field=models.BooleanField(default=False),
        ),
    ]
