# Generated by Django 5.1.2 on 2024-10-14 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
