# Generated by Django 5.1.2 on 2024-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='countryCode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
