# Generated by Django 5.1.2 on 2024-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='countryInitial',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
